version: "2.1"

services:
  code-server:
    build: .
    image: code-server:ready
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - .:/config
    ports:
      - ${PORT}:8443
    restart: unless-stopped
    
