version: "3.1"

services:

  coder:
    build: .
    container_name: coder
    environment:
      - "DOCKER_USER=$USER"
    volumes:
      - ./src:/home/coder/project
    ports:
      - 8080:8080
    
