version: "2.1"

services:

  coder:
    build: .
    environment:
      - "DOCKER_USER=$USER"
    volumes:
      - ~/.config:/home/coder/.config
      - .:/home/coder/project
    ports:
      - ${PORT}:8080
    
